# Generated by Django 5.2.2 on 2025-07-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-issued_date']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_on']},
        ),
    ]
