# Generated by Django 5.2.2 on 2025-07-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_paid_on_invoice_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paid_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
