# Generated by Django 5.1.7 on 2025-08-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_payment_date_created_payment_email_payment_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date_created',
        ),
    ]
