# Generated by Django 5.1.7 on 2025-08-15 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_payment_gateway_reference_alter_invoice_doctor_and_more'),
        ('doctors', '0002_rename_specialty_doctorprofile_specialization'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='invoice_total_nonnegative',
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='uniq_nonnull_transaction_id',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='payment_amount_positive',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='billing_inv_due_dat_e51895_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='billing_inv_is_paid_55f750_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='billing_pay_method_ae4483_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='billing_pay_paid_on_a0fdca_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='gateway_reference',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
