# Generated by Django 5.1.7 on 2025-08-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_remove_invoice_invoice_total_nonnegative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paid_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
