# Generated by Django 5.2.2 on 2025-07-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('reviewed', 'Reviewed')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
