# Generated by Django 5.2.2 on 2025-06-09 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('neurology', 'Neurology'), ('pediatrics', 'Pediatrics'), ('general', 'General Practice')], max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('office_address', models.TextField(blank=True)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
