# Generated by Django 5.2.2 on 2025-06-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='specialty',
            new_name='specialization',
        ),
    ]
